name: Docker Image CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Build the Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/tmc-frontend:latest .

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }} docker.io

      - name: Publish image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/tmc-frontend:latest


  # deploy:
  #   needs: build
  #   runs-on: [aws-ec2]
  #   steps:
  #     - name: Pull image from Docker Hub
  #       run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/tmc-backend:latest

  #     - name: Delete old container
  #       run: |
  #         docker stop tmc-backend-container
  #         docker rm -f tmc-backend-container

  #     - name: Create .env file locally
  #       run: |
  #         touch .env
  #         echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" > .env
  #         echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
  #         echo "TMC_API_CONFIG_KEY=${{ secrets.TMC_API_CONFIG_KEY }}" >> .env
  #         echo "PORT=${{ secrets.PORT }}" >> .env
  #         # Add more environment variables as needed

  #     - name: Run docker container
  #       run: |
  #         docker run -d -p 4000:4000 \
  #           --env-file .env \
  #           --name tmc-backend-container \
  #           ${{ secrets.DOCKERHUB_USERNAME }}/tmc-backend
