name: Docker Image CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Create .env file locally
        run: |
          touch .env.production
          echo "SERVICE_BASE_URL=${{ secrets.SERVICE_BASE_URL }}" > .env.production
          echo "EMAIL=${{ secrets.EMAIL }}" >> .env.production
          echo "EMAIL_PASS=${{ secrets.EMAIL_PASS }}" >> .env.production
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env.production
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env.production
          echo "NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}" >> .env.production
          echo "NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}" >> .env.production
          echo "SERVICE_API_KEY=${{ secrets.SERVICE_API_KEY }}" >> .env.production
          echo "SERVICE_API_KEY_VALUE=${{ secrets.SERVICE_API_KEY_VALUE }}" >> .env.production
          # Add more environment variables as needed

      - name: Build the Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/tmc-frontend:latest .
        env:
         DOCKER_BUILDKIT: 1
          # Include the .env.production file in the build context
        with:
          files: |
            .env.production

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }} docker.io

      - name: Publish image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/tmc-frontend:latest


  deploy:
    needs: build
    runs-on: [tmc_aws_ec2]
    steps:

      - name: Stop old container
        run: |
          CONTAINER_ID=$(docker ps -q -f name=tmc-frontend-container)
          if [ -z "$CONTAINER_ID" ]; then
            echo "Container not found. Skipping stop action."
            exit 0
          else
            echo "Container found. Stopping..."
            docker stop tmc-frontend-container
            echo "Container stopped."
          fi
        shell: bash

      - name: Delete old container
        run: |
          docker rm -f tmc-frontend-container

      - name: Remove old Docker images
        run: |
          docker images -q ${{ secrets.DOCKERHUB_USERNAME }}/tmc-frontend | xargs -I {} docker rmi {}
        shell: bash

      - name: Pull image from Docker Hub
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/tmc-frontend:latest

      - name: Create .env file locally
        run: |
          touch .env.production
          echo "SERVICE_BASE_URL=${{ secrets.SERVICE_BASE_URL }}" > .env.production
          echo "EMAIL=${{ secrets.EMAIL }}" >> .env.production
          echo "EMAIL_PASS=${{ secrets.EMAIL_PASS }}" >> .env.production
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env.production
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env.production
          echo "NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}" >> .env.production
          echo "NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}" >> .env.production
          echo "SERVICE_API_KEY=${{ secrets.SERVICE_API_KEY }}" >> .env.production
          echo "SERVICE_API_KEY_VALUE=${{ secrets.SERVICE_API_KEY_VALUE }}" >> .env.production
          # Add more environment variables as needed

      - name: Run docker container
        run: |
          docker run -d -p 3000:3000 \
            --env-file .env.production \
            --name tmc-frontend-container \
            ${{ secrets.DOCKERHUB_USERNAME }}/tmc-frontend
